### ISSUE TITLE
System.NullReferenceException on Undo

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/AvaloniaEdit#425]
## How to simulate:

- Clone latest master 88625c4491af8ca6fa9127872ae1f1099fd06392
- Open `AvaloniaEdit.sln`
- Run `AvaloniaEdit.Demo`
- Go to line 62
- Press `Enter` key
- Click on Button `Insert Snipet` 
- Edit name in `aaa` and press `Enter` key for confirm the change
- Press `CTRL+Z` four times
- The exception will be thrown

**Comment by Rekkonnect** [comment]
The action of adding a snippet adds multiple lines and thus exposes the lack of checking whether the invalidated line range is out of bounds. The call stack shows that the exception is ultimately thrown by TextMateSharp because it attempts to read the line at the given index, without checking whether it's in bounds. This can be retrieved via the `GetNumberOfLines()` method from the model, and evaluated such that `InvalidateLineRange(int, int)` doesn't run the loop with out of bounds indexes.

@danipen Does this belong to https://github.com/danipen/TextMateSharp? Then this issue would track the respective issue in that repo.
