### ISSUE TITLE
Problem with displaying the auto-completion list

### ISSUE THREAD

**Issue by gsa-m** [AvaloniaUI/AvaloniaEdit#449]
The list display problems start with Avalonia version 11.1.0 (the previous version 11.0.13 works correctly). 

Error: [Binding]An error occurred binding 'Content' to 'Content' at 'Content': 'Unable to cast object of type 'System.String' to type 'AvaloniaEdit.CodeCompletion.ICompletionData'.' (ContentPresenter #48657561)

![2024-08-23_10-46-54](https://github.com/user-attachments/assets/7c2f061b-238f-4233-8b3b-b9eb7156fee4)

**Comment by mgarstenauer** [comment]
I am seeing the same issue (Avalonia 11.1.3, AvaloniaEdit 11.1.0). Changing the control template [here](https://github.com/AvaloniaUI/AvaloniaEdit/blob/a9b6b20af32eeebd143508355dd24e3a23176902/src/AvaloniaEdit/CodeCompletion/CompletionList.xaml#L27) to 

```xaml
<ContentPresenter Content="{Binding Content, Mode=OneTime}" />
```

fixes the issue – at least in my app. Not sure what the underlying cause is. Some changes in the binding system?

**Comment by AlexKerman** [comment]
Another solution (in a ICompletionData implementarion):

public object Content => this;
